/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : xdoc2txt
 #	author : miyako
 #	2018/09/03
 #
 # --------------------------------------------------------------------------------*/



// --- xdoc2txt
void xdoc2txt(sLONG_PTR *pResult, PackagePtr pParams);
